### PR TITLE
Add bandit checks

### PR DESCRIPTION
**Pull request by leonholub**
## Purpose
Bandit is a security linter from OpenStack Security. See [GitHub Repo](https://github.com/openstack/bandit) for documentation and further information on bandit. It's purpose is to check for common coding errors and security issues in our python code before each commit.

## Approach
Added a new step in the Drone pipeline that will execute bandit after the existing tests and give a report on high-level security issues.

### Open Questions and Pre-Merge TODOs
- [ ] Remove high-level security issues from the codebase or make sure the issue is not affecting us and adding an exception to the bandit config.
- [ ] Lower the sensitivity for bandit and repeat step 1 until we have no low-level security issues

### CODE REVIEW

**Comment by Menda** [comment]
I need to take a closer look to it, but looks good this Bandit. BTW, you have many commits coming from other PR's. Needs rebase

**Comment by leonholub** [comment]
You can take a look, but @glind and i decided to move the checks elsewhere since TolaActivity contains code which we don't use anymore and this is causing most of the warnings.

**Comment by Menda** [comment]
Probably we can move it better to ActivityAPI. There we don't have much dead code

**Comment by leonholub** [comment]
That was the plan

**Pull request closed without merging**
