### PR TITLE
Exceed amount editors

### PR DESCRIPTION
**Pull request by jefmoura**
## Purpose
We didn't have an official email template for this notification. Now, we're updating it.

### Furter Info
Related ticket: https://github.com/Humanitec/ActivityAPI/issues/145

### CODE REVIEW

**Comment by jefmoura** [comment]
The workflow's signals send the Email, so if I move the templates to ActivityAPI the tests in TolaAcvitiy won't work. Should we move even the signals' tests to ActivityAPI?

**Comment by Menda** [comment]
I think we should find a way to install the templates in the package as well, as many other Django applications are doing when they internally need a template.

**Comment by jefmoura** [comment]
As I talked to @Menda I sill have to figure out how to import the HTML template with the TolaActivity py package.

**Comment by Menda** [comment]
Create a ticket and post it here, so we don't lose track of that

**Comment by jefmoura** [comment]
Yes, sir @Menda! I have already created a ticket for it. https://github.com/Humanitec/ActivityAPI/issues/233

**Pull request merged**
